package main

// UserAgents for rotation (from Python's core/others.py)
var UserAgents = []string{
	"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.991",
	"Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; A1-810 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30",
	"Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0",
	"Mozilla/5.0 (PLAYSTATION 3 4.81) AppleWebKit/531.22.8 (KHTML, like Gecko)",
	"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 OPR/48.0.2685.52",
	"Mozilla/5.0 (SMART-TV; X11; Linux armv7l) AppleWebKit/537.42 (KHTML, like Gecko) Chromium/25.0.1349.2 Chrome/25.0.1349.2 Safari/537.42",
	"Mozilla/5.0 (Windows NT 6.0; WOW64; Trident/7.0; rv:11.0) like Gecko",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko)",
	"Mozilla/5.0 (PlayStation 4 5.01) AppleWebKit/601.2 (KHTML, like Gecko)",
}

// DOMSourcesSinks for XSS detection (126 patterns from oralyzer.py lines 87-213)
var DOMSourcesSinks = []string{
	"location.href",
	"location.hash",
	"location.search",
	"location.pathname",
	"document.URL",
	"window.name",
	"document.referrer",
	"document.documentURI",
	"document.baseURI",
	"document.cookie",
	"location.hostname",
	"jQuery.globalEval",
	"eval",
	"Function",
	"execScript",
	"setTimeout",
	"setInterval",
	"setImmediate",
	"msSetImmediate",
	"script.src",
	"script.textContent",
	"script.text",
	"script.innerText",
	"script.innerHTML",
	"script.appendChild",
	"script.append",
	"document.write",
	"document.writeln",
	"jQuery",
	"jQuery.$",
	"jQuery.constructor",
	"jQuery.parseHTML",
	"jQuery.has",
	"jQuery.init",
	"jQuery.index",
	"jQuery.add",
	"jQuery.append",
	"jQuery.appendTo",
	"jQuery.after",
	"jQuery.insertAfter",
	"jQuery.before",
	"jQuery.insertBefore",
	"jQuery.html",
	"jQuery.prepend",
	"jQuery.prependTo",
	"jQuery.replaceWith",
	"jQuery.replaceAll",
	"jQuery.wrap",
	"jQuery.wrapAll",
	"jQuery.wrapInner",
	"jQuery.prop.innerHTML",
	"jQuery.prop.outerHTML",
	"element.innerHTML",
	"element.outerHTML",
	"element.insertAdjacentHTML",
	"iframe.srcdoc",
	"location.replace",
	"location.assign",
	"window.open",
	"iframe.src",
	"javascriptURL",
	"jQuery.attr.onclick",
	"jQuery.attr.onmouseover",
	"jQuery.attr.onmousedown",
	"jQuery.attr.onmouseup",
	"jQuery.attr.onkeydown",
	"jQuery.attr.onkeypress",
	"jQuery.attr.onkeyup",
	"element.setAttribute.onclick",
	"element.setAttribute.onmouseover",
	"element.setAttribute.onmousedown",
	"element.setAttribute.onmouseup",
	"element.setAttribute.onkeydown",
	"element.setAttribute.onkeypress",
	"element.setAttribute.onkeyup",
	"createContextualFragment",
	"document.implementation.createHTMLDocument",
	"xhr.open",
	"xhr.send",
	"fetch",
	"fetch.body",
	"xhr.setRequestHeader.name",
	"xhr.setRequestHeader.value",
	"jQuery.attr.href",
	"jQuery.attr.src",
	"jQuery.attr.data",
	"jQuery.attr.action",
	"jQuery.attr.formaction",
	"jQuery.prop.href",
	"jQuery.prop.src",
	"jQuery.prop.data",
	"jQuery.prop.action",
	"jQuery.prop.formaction",
	"form.action",
	"input.formaction",
	"button.formaction",
	"button.value",
	"element.setAttribute.href",
	"element.setAttribute.src",
	"element.setAttribute.data",
	"element.setAttribute.action",
	"element.setAttribute.formaction",
	"webdatabase.executeSql",
	"document.domain",
	"history.pushState",
	"history.replaceState",
	"xhr.setRequestHeader",
	"websocket",
	"anchor.href",
	"anchor.target",
	"JSON.parse",
	"localStorage.setItem.name",
	"localStorage.setItem.value",
	"sessionStorage.setItem.name",
	"sessionStorage.setItem.value",
	"element.outerText",
	"element.innerText",
	"element.textContent",
	"element.style.cssText",
	"RegExp",
	"location.protocol",
	"location.host",
	"input.value",
	"input.type",
	"document.evaluate",
}

// WaybackDorks for filtering URLs (from wayback.py lines 6-28)
var WaybackDorks = []string{
	`.*\?next=.*`,
	`.*\?url=.*`,
	`.*\?target=.*`,
	`.*\?rurl=.*`,
	`.*\/dest=.*`,
	`.*\/destination=.*`,
	`.*\?redir=.*`,
	`.*\?redirect_uri=.*`,
	`.*\?return=.*`,
	`.*\?return_path.*`,
	`.*\/cgi-bin\/redirect\.cgi\?.*`,
	`.*\?checkout_url=.*`,
	`.*\?image_url=.*`,
	`.*\/out\?.*`,
	`.*\?continue=.*`,
	`.*\?view=.*`,
	`.*\/redirect\/.*`,
	`.*\?go=.*`,
	`.*\?redirect=.*`,
	`.*\?externallink=.*`,
	`.*\?nextURL=.*`,
}

// CRLFPayloads for CRLF injection testing (25 payloads from crlf.py lines 4-30)
var CRLFPayloads = []string{
	`%0d%0aLocation:www.google.com%0d%0a`,
	`%0d%0aSet-Cookie:name=ch33ms;`,
	"\r\n\tSet-Cookie:name=ch33ms;",
	"\r\tSet-Cookie:name=ch33ms;",
	`%E5%98%8A%E5%98%8DLocation:www.google.com`,
	"\rSet-Cookie:name=ch33ms;",
	"\r%20Set-Cookie:name=ch33ms;",
	"\r\nSet-Cookie:name=ch33ms;",
	"\r\n%20Set-Cookie:name=ch33ms;",
	"\rSet-Cookie:name=ch33ms;",
	`%u000ASet-Cookie:name=ch33ms;`,
	"\r%20Set-Cookie:name=ch33ms;",
	`%23%0D%0ALocation:www.google.com;`,
	"\r\nSet-Cookie:name=ch33ms;",
	"\r\n%20Set-Cookie:name=ch33ms;",
	"\r\n\tSet-Cookie:name=ch33ms;",
	"\r\tSet-Cookie:name=ch33ms;",
	`%5cr%5cnLocation:www.google.com`,
	`%E5%98%8A%E5%98%8D%0D%0ASet-Cookie:name=ch33ms;`,
	"\rSet-Cookie:name=ch33ms;",
	"\r%20Set-Cookie:name=ch33ms;",
	"\r\nSet-Cookie:name=ch33ms;",
	"\r\n%20Set-Cookie:name=ch33ms;",
	"\r\n\tSet-Cookie:name=ch33ms;",
	"\r\tSet-Cookie:name=ch33ms;",
}

// GoogleVariants for CRLF detection (checking if Location header redirects to Google)
var GoogleVariants = []string{
	"https://www.google.com",
	"http://www.google.com",
	"google.com",
	"www.google.com",
}
